# Generated by Django 6.0 on 2025-12-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPlantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nomeCientifico', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('regiao', models.CharField(max_length=255)),
            ],
        ),
    ]
